apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: sonarr
  name: sonarr
  namespace: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      containers:
      - name: main
        env:
        - name: TZ
          value: Europe/Berlin
        # Database password from postgresql-vecto-sonarr-auth (single source of truth)
        - name: SONARR__POSTGRES__USER
          valueFrom:
            secretKeyRef:
              name: postgresql-vecto-sonarr-auth
              key: username
              optional: false
        - name: SONARR__POSTGRES__PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-vecto-sonarr-auth
              key: password
              optional: false
        envFrom:
        - configMapRef:
            name: sonarr-env
        image: ghcr.io/home-operations/sonarr:4.0.16.2946
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /ping
            port: 8989
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort: 8989
          name: main
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /ping
            port: 8989
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        startupProbe:
          failureThreshold: 60
          httpGet:
            path: /ping
            port: 8989
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /config
          name: sonarr-config
        - mountPath: /data
          name: data
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      volumes:
      - name: sonarr-config
        persistentVolumeClaim:
          claimName: sonarr-pvc
      - name: data
        hostPath:
         path: /mnt/data/
         type: Directory
