---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-env
  namespace: media
data:
  SONARR__APP__THEME: "dark"
  # SONARR__SERVER__URLBASE: "/series"
  SONARR__POSTGRES__HOST: ${quote}${DEFAULT_POSTGRES_HOST}${quote}
  SONARR__POSTGRES__PORT: ${quote}${DEFAULT_POSTGRES_PORT}${quote}
  SONARR__POSTGRES__MAINDB: sonarr_main
  SONARR__POSTGRES__LOGDB: sonarr_log
  SONARR__POSTGRES__USER: ${DEFAULT_POSTGRES_SONARR_USER}
  SONARR__LOG__ANALYTICSENABLED: "false"
  SONARR__LOG__LEVEL: "INFO"
