---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: security-postgres-pv
  namespace: security
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/k3s/data/security-postgres
  volumeMode: Filesystem
