---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: security-postgres-pvc
  namespace: security
spec:
  storageClassName: "local-path"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
