---
apiVersion: v1
kind: Secret
metadata:
  name: couchdb-secret
  namespace: default
type: Opaque
stringData:
  COUCHDB_USER: ${quote}${COUCHDB_USER}${quote}
  COUCHDB_PASSWORD : ${quote}${COUCHDB_PASSWORD}${quote}
