---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data-pvc
  namespace: default
spec:
  storageClassName: "local-path"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-config-pvc
  namespace: default
spec:
  storageClassName: "local-path"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi