---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
  namespace: default
  labels:
    app.kubernetes.io/name: couchdb
spec:
  selector:
    app.kubernetes.io/name: couchdb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5984
