---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-home-cert
  namespace: edge
data:
  dynamic-home-cert.yaml: |
    tls:
      certificates:
        - certFile: "/certs/tls.crt"
          keyFile: "/certs/tls.key"
