nameOverride: traefik
fullnameOverride: traefik
namespaceOverride: edge
deployment:
  enabled: true
  kind: DaemonSet
service:
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Local # https://kubernetes.io/docs/tutorials/services/source-ip/
    loadBalancerIP: ${quote}${TRAEFIK_LB_IP}${quote}
securityContext:
  seccompProfile:
    type: RuntimeDefault
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
tlsStore:
  default:
    defaultCertificate:
      secretName: ${quote}${CERTIFICATE_NAME}${quote}
ingressClass:
  enabled: true
  isDefaultClass: true
ports:
  web:
    port: 80
    expose:
      enabled: true
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    port: 443
    expose:
      enabled: true
  smb:
    port: 445
    expose:
      enabled: true
    protocol: TCP
  websocket:
    port: 9999
    expose:
      enabled: true
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.home.${DOMAIN_NAME}`) && PathPrefix(`/dashboard`) || Host(`traefik.home.${DOMAIN_NAME}`) && PathPrefix(`/api`)
    middlewares: [{name: local-ipallowlist, namespace: edge}]
    entryPoints: [websecure, web]
    services:
      - name: api@internal
        kind: TraefikService
