---
nameOverride: traefik
fullnameOverride: traefik
namespaceOverride: edge
deployment:
  enabled: true
  kind: DaemonSet
# TODO: enable access logs and feed them to crowdsec!
# logs:
#   access:
#     enabled: true
#     fields:
#       defaultMode: keep
#       names:
#         Headers.X-Forwarded-For: keep
#         Headers.User-Agent: keep
service:
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Local # https://kubernetes.io/docs/tutorials/services/source-ip/
    loadBalancerIP: ${quote}${TRAEFIK_LB_IP}${quote}
securityContext:
  seccompProfile:
    type: RuntimeDefault
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
tlsStore:
  default:
    defaultCertificate:
      secretName: ${quote}${CERTIFICATE_NAME}${quote}
ingressClass:
  enabled: true
  isDefaultClass: true
ports:
  web:
    port: 80
    expose:
      enabled: true
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "192.168.178.1/24"
        - "10.0.0.0/8"
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    port: 443
    expose:
      enabled: true
  smb:
    port: 445
    expose:
      enabled: true
    protocol: TCP
ingressRoute:
  dashboard:
    enabled: true
