nameOverride: traefik
fullnameOverride: traefik
namespaceOverride: edge
deployment:
  enabled: true
  kind: DaemonSet
volumes:
  - name: dynamic-home-cert
    mountPath: "/config"
    readOnly: true
    type: configMap
  - name: ${CERTIFICATE_NAME_HOME}
    mountPath: /certs
    readOnly: true
    type: secret
additionalArguments:
  - "--providers.file.filename=/config/dynamic-home-cert.yaml"
service:
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Local # https://kubernetes.io/docs/tutorials/services/source-ip/
    # loadBalancerIP: "192.168.178.130"
    loadBalancerClass: io.cilium/node
logs:
  access:
    enabled: true
    format: json
    filters:
      statuscodes: "400-599" # log failed http requests
    # collect logs as in-memory buffer before writing into log file
    bufferingSize: 0
    fields:
      headers:
        defaultMode: keep
    #     names:
    #         User-Agent: keep # log user agent strings
experimental:
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.2
securityContext:
  seccompProfile:
    type: RuntimeDefault
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
tlsStore:
  default:
    defaultCertificate:
      secretName: ${CERTIFICATE_NAME}
ingressClass:
  enabled: true
  isDefaultClass: true
ports:
  web:
    port: 80
    expose:
      enabled: true
    # redirections:
    #   entryPoint:
    #     to: websecure
    #     scheme: https
    #     permanent: true
  websecure:
    port: 443
    expose:
      enabled: true
  smb:
    port: 445
    expose:
      enabled: true
    protocol: TCP
  websocket:
    port: 9999
    expose:
      enabled: true
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.home.${DOMAIN_NAME}`) && PathPrefix(`/dashboard`) || Host(`traefik.home.${DOMAIN_NAME}`) && PathPrefix(`/api`)
    middlewares: [{ name: local-ipallowlist, namespace: edge }]
    entryPoints: [websecure, web]
    services:
      - name: api@internal
        kind: TraefikService
