apiVersion: v1
kind: Secret
metadata:
  name: default-postgres-auth
  namespace: default
type: Opaque
stringData:
  postgres-password: ${quote}${DEFAULT_POSTGRES_SYSTEM_PASSWORD}${quote}
  password: ${quote}${DEFAULT_POSTGRES_DEFAULT_USER_PASSWORD}${quote}
