---
global:
  security:
    allowInsecureImages: "true"
image:
  registry: docker.io
  repository: tensorchord/pgvecto-rs
  tag: pg17-v0.4.0-rootless
auth:
  username: defaultuser
  existingSecret: default-postgres-auth
# nameOverride: default-postgresql
# fullnameOverride: default-postgresql
# namespaceOverride: default
primary:
  persistence:
    enabled: true
    existingClaim: default-postgres-pvc
  containerSecurityContext:
    runAsGroup: 1000
    runAsUser: 1000
