---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./default-postgres-auth-secret.yaml
  - ./default-postgres-backup-secret.yaml
  - ./default-postgres-pvc.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: default-postgres-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
