---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./alloy-cm.yaml
  - ./helm-release.yaml
  - ./ingressroute.yaml
configMapGenerator:
  - name: grafana-alloy-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
