---
apiVersion: v1
kind: Secret
metadata:
  name: tinyauth-secret
  namespace: security
type: Opaque
stringData:
  pocketid-client-secret: "${TINYAUTH_POCKETID_CLIENT_SECRET}"
  values.yaml: |
    tinyauth:
      oauth:
        providers:
          - id: "pocketid"
            clientSecret: "${TINYAUTH_POCKETID_CLIENT_SECRET}"
