---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./portainer-ingressroute.yaml
  - ./portainer-pvc.yaml
  - ./portainer.yaml
configMapGenerator:
  - name: portainer-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
