---
apiVersion: v1
kind: Secret
metadata:
  name: shiori-secret
  namespace: default
  labels:
    app.kubernetes.io/name: shiori
type: Opaque
stringData:
  SHIORI_HTTP_SECRET_KEY: ${quote}${SHIORI_HTTP_SECRET_KEY}${quote}
