---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shiori-pvc
  namespace: default
  labels:
    app.kubernetes.io/name: shiori
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
