---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: beszel-agent-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: beszel-agent
type: Opaque
stringData:
  key: ${quote}${BESZEL_AGENT_PUB_KEY}${quote}
  token: ${quote}${BESZEL_AGENT_TOKEN}${quote}
