---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-hub-pvc
  namespace: monitoring
  labels:
    app.kubernetes.io/name: beszel-hub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
