---
apiVersion: v1
kind: Secret
metadata:
  name: beszel-agent-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: beszel-agent
type: Opaque
stringData:
  key: ${quote}${BESZEL_KEY}${quote}
