---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoy-home-tls
  namespace: network
spec:
  secretName: envoy-home-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "${quote}${CERTIFICATE_DOMAIN_HOME}${quote}"
