---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./uptime-kuma-ingressroute.yaml
  - ./uptime-kuma-pvc.yaml
  - ./uptime-kuma.yaml
configMapGenerator:
  - name: uptime-kuma-helm-values
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
