---
apiVersion: v1
kind: Secret
metadata:
  name: linkding-secret
  namespace: default
type: Opaque
stringData:
  LD_SUPERUSER_NAME: ${quote}${LINKDING_SUPERUSER_NAME}${quote}
  LD_SUPERUSER_PASSWORD: ${quote}${LINKDING_SUPERUSER_PASSWORD}${quote}
