---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./security-postgres-backup-cj.yaml
  - ./security-postgres-backup-secret.yaml
