---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icloudpd-config-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: icloud-to-immich
    app.kubernetes.io/component: downloader
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
