---
apiVersion: v1
kind: Secret
metadata:
  name: immich-go-secret
  namespace: media
  labels:
    app.kubernetes.io/name: icloud-to-immich
    app.kubernetes.io/component: uploader
type: Opaque
stringData:
  # Immich API credentials
  IMMICH_SERVER_URL: ${quote}${IMMICH_SERVER_URL}${quote}
  IMMICH_API_KEY: ${quote}${IMMICH_API_KEY}${quote}
