podAnnotations:
  reloader.stakater.com/auto: "true"
annotations:
  reloader.stakater.com/auto: "true"

admin:
  existingSecret: "grafana-secret"
  userKey: admin-user
  passwordKey: admin-password

persistence:
  type: pvc
  enabled: false
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  size: 6Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local:80
        isDefault: true
        jsonData:
          timeInterval: "30s"
          queryTimeout: "60s"
          httpMethod: "POST"
        editable: false

sidecar:
  dashboards:
    enabled: true
    searchNamespace: "monitoring"

# Add resource limits for homelab
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
