---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "^10.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      reconcileStrategy: Revision
  valuesFrom:
    - kind: ConfigMap
      name: grafana-helm-values
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
