persistence:
  type: pvc
  enabled: false
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  size: 6Gi

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
     - name: InfluxDB_v2_Flux
       type: influxdb
       access: proxy
       url: ${INFLUXDB2_HOST}
       jsonData:
         version: Flux
         organization: homelab-k3s
         defaultBucket: telegraf
         tlsSkipVerify: true
       secureJsonData:
         token: ${INFLUXDB2_GRAFANA_TOKEN}
