---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-node-exporter
      version: "4.51.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      reconcileStrategy: Revision
  valuesFrom:
    - kind: ConfigMap
      name: node-exporter-helm-values
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
