apiVersion: v1
kind: Service
metadata:
  name: spoolman
  namespace: default
  labels:
    app.kubernetes.io/name: spoolman
spec:
  selector:
    app.kubernetes.io/name: spoolman
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
