apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: default
  labels:
    app.kubernetes.io/name: samba
spec:
  type: ClusterIP # NodePort
  selector:
    app.kubernetes.io/name: samba
  ports:
  - name: netbios-ns
    port: 137
    protocol: UDP
  - name: netbios-dgm
    port: 138
    protocol: UDP
  - name: netbios-ssn
    port: 139
    protocol: TCP
  - name: smb
    port: 445
    protocol: TCP
