apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: samba
  namespace: default
  labels:
    app.kubernetes.io/name: samba
spec:
  entryPoints:
    - smb
  routes:
  - match: HostSNI(`*`)
    services:
    - name: samba
      namespace: default
      port: 445
