---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gatus-secret
  namespace: monitoring
type: Opaque
stringData:
  TELEGRAM_TOKEN: ${quote}${TELEGRAM_BOT_TOKEN}${quote}
  TELEGRAM_CHAT_ID: ${quote}${TELEGRAM_BOT_CHAT_ID}${quote}
