---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: gatus-secret
  namespace: monitoring
type: Opaque
stringData:
  PUSHOVER_STATUS_TOKEN: ${quote}${PUSHOVER_STATUS_TOKEN}${quote}
  PUSHOVER_USER_KEY: ${quote}${PUSHOVER_USER_KEY}${quote}
  H_CLOUD_PUSHOVER_CLUSTER_ENDPOINT_TOKEN: ${quote}${H_CLOUD_PUSHOVER_CLUSTER_ENDPOINT_TOKEN}${quote}
