---
apiVersion: v1
kind: Secret
metadata:
  name: gatus-secret
  namespace: monitoring
type: Opaque
stringData:
  TELEGRAM_TOKEN: ${quote}${TELEGRAM_BOT_TOKEN}${quote}
  TELEGRAM_CHAT_ID: ${quote}${TELEGRAM_BOT_CHAT_ID}${quote}
