---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/name: paperless
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: main
        env:
        - name: PAPERLESS_APPS
          value: "allauth.socialaccount.providers.openid_connect"
        - name: PAPERLESS_PORT
          value: "8000"
        - name: PAPERLESS_OCR_LANGUAGE
          value: deu
        - name: PAPERLESS_TIME_ZONE
          value: "Europe/Berlin"
        - name: PAPERLESS_URL
          value: "https://docs.${DOMAIN_NAME}"
        - name: PAPERLESS_USE_X_FORWARD_HOST # to be verified
          value: "true"
        - name: PAPERLESS_TASK_WORKERS
          value: "2"
        - name: USERMAP_UID
          value: "1000"
        - name: USERMAP_GID
          value: "1000"
        # Database credentials from postgresql-vecto-paperless-auth (single source of truth)
        - name: PAPERLESS_DBHOST
          value: postgresql-vecto-cluster-rw.default.svc.cluster.local # ${quote}${DEFAULT_POSTGRES_HOST}${quote}
        - name: PAPERLESS_DBPORT
          value: ${quote}${DEFAULT_POSTGRES_PORT}${quote}
        - name: PAPERLESS_DBNAME
          value: ${quote}${DEFAULT_POSTGRES_PAPERLESS_DATABASE}${quote}
        - name: PAPERLESS_DBUSER
          valueFrom:
            secretKeyRef:
              name: postgresql-vecto-paperless-auth
              key: username
        - name: PAPERLESS_DBPASS
          valueFrom:
            secretKeyRef:
              name: postgresql-vecto-paperless-auth
              key: password
        envFrom:
        - secretRef:
            name: paperless
        image: ghcr.io/paperless-ngx/paperless-ngx:2.20.6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort: 8000
          name: main
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 50m
            memory: 200Mi
        startupProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/src/paperless/data
          name: paperless-data
        - mountPath: /usr/src/paperless/media
          name: paperless-media
        - mountPath: :/usr/src/paperless/consume
          name: consume
        - mountPath: /usr/src/paperless/export
          name: export
        # reason: https://github.com/paperless-ngx/paperless-ngx/issues/9609 --> https://github.com/just-containers/s6-overlay/issues/600
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   capabilities:
        #     drop:
        #       - ALL
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      volumes:
      - name: paperless-data
        persistentVolumeClaim:
          claimName: paperless-data-pvc
      - name: paperless-media
        persistentVolumeClaim:
          claimName: paperless-media-pvc
      - name: consume
        hostPath:
         path: /mnt/data/media/docs/consume
         type: Directory
      - name: export
        hostPath:
         path: /mnt/data/media/docs/export
         type: Directory
