apiVersion: v1
kind: Secret
metadata:
  name: paperless-init-db
  namespace: default
type: Opaque
stringData:
  PGUSER: "postgres"
  PGPASSWORD: ${quote}${DEFAULT_POSTGRES_SYSTEM_PASSWORD}${quote}
  PGHOST: ${DEFAULT_POSTGRES_HOST}
  PAPERLESS_DBUSER: ${quote}${DEFAULT_POSTGRES_PAPERLESS_USER}${quote}
  PAPERLESS_DBPASS: ${quote}${DEFAULT_POSTGRES_PAPERLESS_USER_PASSWORD}${quote}
  PAPERLESS_DBNAME: ${quote}${DEFAULT_POSTGRES_PAPERLESS_DATABASE}${quote}
