---
apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: default
  labels:
    app.kubernetes.io/name: paperless
spec:
  selector:
    app.kubernetes.io/name: paperless
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000 
