---
apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secrets
  namespace: default
type: Opaque
stringData:
  NEXTAUTH_SECRET: ${quote}${KARAKEEP_NEXTAUTH_SECRET}${quote}
  MEILI_MASTER_KEY: ${quote}${KARAKEEP_MEILI_MASTER_KEY}${quote}
  NEXT_PUBLIC_SECRET: ${quote}${KARAKEEP_NEXT_PUBLIC_SECRET}${quote}
  # OPENAI_API_KEY: ${quote}${KARAKEEP_OPENAI_APIKEY}${quote}
  NEXTAUTH_URL: ${quote}https://bookmarks.${DOMAIN_NAME}${quote}
  DISABLE_SIGNUPS: "true"
