apiVersion: apps/v1
kind: Deployment
metadata:
  name: karakeep
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: karakeep
  template:
    metadata:
      labels:
        app.kubernetes.io/name: karakeep
    spec:
      containers:
        - name: karakeep
          image: ghcr.io/karakeep-app/karakeep:0.25.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: KARAKEEP_VERSION
              value: release
            - name: MEILI_ADDR
              value: http://meilisearch.default.svc.cluster.local
            - name: BROWSER_WEB_URL
              value: http://chrome.default.svc.cluster.local
            - name: DATA_DIR
              value: /data
            - name: COREPACK_INTEGRITY_KEYS # workaround https://github.com/karakeep-app/karakeep/issues/1015
              value: "0"
            # Add OPENAI_API_KEY to the ConfigMap if necessary
          volumeMounts:
            - mountPath: /data
              name: data
          envFrom:
            - secretRef:
                name: karakeep-secrets
          resources:
            limits:
              cpu: 200m
              memory: 750Mi
            requests:
              cpu: 10m
              memory: 200Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: karakeep-pvc
