apiVersion: v1
kind: Service
metadata:
  name: karakeep
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: karakeep
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
