---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: karakeep
  namespace: default
  labels:
    app.kubernetes.io/name: karakeep
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - kind: Rule
    match: Host(`bookmarks.${DOMAIN_NAME}`)
    priority: 10
    services:
    - kind: Service
      name: karakeep
      namespace: default
      passHostHeader: true
      port: 80
      scheme: http
