---
apiVersion: v1
kind: Secret
metadata:
  name: donetick-secret
  namespace: default
  labels:
    app.kubernetes.io/name: donetick
type: Opaque
stringData:
  DT_JWT_SECRET: ${quote}${DONETICK_JWT_SECRET}${quote}
  DT_IS_USER_CREATION_DISABLED: "true"
  DT_TELEGRAM_TOKEN: ${quote}${TELEGRAM_BOT_TOKEN}${quote}
  DT_EMAIL_HOST: ${RESEND_SMTP_HOST}
  DT_EMAIL_PORT: ${quote}${RESEND_SMTP_PORT}${quote}
  DT_EMAIL_KEY: ${quote}${RESEND_API_KEY}${quote}
  DT_EMAIL_EMAIL: ${quote}donetick@${DOMAIN_NAME}${quote}
  DT_EMAIL_USER: resend
  DT_EMAIL_APP_HOST: https://todo.${DOMAIN_NAME}
