---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: donetick
  namespace: default
  labels:
    app.kubernetes.io/name: donetick
spec:
  type: ClusterIP
  ports:
    - port: 2021
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: donetick
