---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-state-metrics
      version: "5.37.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      reconcileStrategy: Revision
  valuesFrom:
    - kind: ConfigMap
      name: kube-state-metrics-helm-values
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
