---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: fritzbox-cloudflare-dyndns-credentials
  namespace: edge
type: Opaque
stringData:
  user: ${quote}${FRITZBOX_DDNS_USERNAME}${quote}
  password: ${quote}${FRITZBOX_DDNS_PASSWORD}${quote}
