---
fullnameOverride: seerr

image:
  tag: "v3.1.0"

extraEnv:
  - name: TZ
    value: Europe/Berlin
  - name: LOG_LEVEL
    value: info

config:
  persistence:
    existingClaim: seerr-pvc

ingress:
  enabled: false

resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: "2"
    memory: 2Gi
