---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: whisper-money-secret
  namespace: default
  labels:
    app.kubernetes.io/name: whisper-money
type: Opaque
stringData:
  APP_KEY: ${quote}${WHISPER_MONEY_APP_KEY}${quote}
  RESEND_API_KEY: ${quote}${RESEND_API_KEY}${quote}
