---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: whisper-money-mysql-secret
  namespace: default
  labels:
    app.kubernetes.io/name: whisper-money
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ${quote}${WHISPER_MONEY_MYSQL_ROOT_PASSWORD}${quote}
  MYSQL_PASSWORD: ${quote}${WHISPER_MONEY_DB_PASSWORD}${quote}
