---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security-postgres-cnpg
  namespace: flux-system
spec:
  interval: 30m
  path: ./clusters/building-blocks/persistency/apps/security-postgres-cnpg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  targetNamespace: security
  dependsOn:
    - name: cloudnative-pg
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
