
apiVersion: v1
kind: Secret
metadata:
  name: hoarder-secrets
  namespace: default
type: Opaque
stringData:
  NEXTAUTH_SECRET: ${quote}${HOARDER_NEXTAUTH_SECRET}${quote}
  MEILI_MASTER_KEY: ${quote}${HOARDER_MEILI_MASTER_KEY}${quote}
  NEXT_PUBLIC_SECRET: ${quote}${HOARDER_NEXT_PUBLIC_SECRET}${quote}
  # OPENAI_API_KEY: ${quote}${HOARDER_OPENAI_APIKEY}${quote}
  NEXTAUTH_URL: ${quote}https://bookmarks.${DOMAIN_NAME}${quote}
  OAUTH_CLIENT_ID: ${quote}${HOARDER_OAUTH_CLIENT_ID}${quote}
  OAUTH_CLIENT_SECRET: ${quote}${HOARDER_OAUTH_CLIENT_SECRET}${quote}
  OAUTH_WELLKNOWN_URL: "https://auth.geckeler.dev/application/o/hoarder/.well-known/openid-configuration"
  OAUTH_PROVIDER_NAME: "authentik"
  OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: "true"
  DISABLE_SIGNUPS: "true"
