
apiVersion: v1
kind: Secret
metadata:
  name: hoarder-secrets
  namespace: default
type: Opaque
stringData:
  NEXTAUTH_SECRET: ${quote}${HOARDER_NEXTAUTH_SECRET}${quote}
  MEILI_MASTER_KEY: ${quote}${HOARDER_MEILI_MASTER_KEY}${quote}
  NEXT_PUBLIC_SECRET: ${quote}${HOARDER_NEXT_PUBLIC_SECRET}${quote}
  # OPENAI_API_KEY: ${quote}${HOARDER_OPENAI_APIKEY}${quote}
