---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./chrome-deploy.yaml
  - ./chrome-svc.yaml
  - ./hoarder-deploy.yaml
  - ./hoarder-ingressroute.yaml
  - ./hoarder-pvc.yaml
  - ./hoarder-secrets.yaml
  - ./hoarder-svc.yaml
  - ./meilisearch-deploy.yaml
  - ./meilisearch-pvc.yaml
  - ./meilisearch-svc.yaml
