---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-secret
  namespace: default
type: Opaque
stringData:
  MONGO_USER: ${quote}${MONGODB_UNIFI_USER}${quote}
  MONGO_PASS: ${quote}${MONGODB_UNIFI_PASSWORD}${quote}
  MONGO_HOST: "mongodb.default.svc.cluster.local"
  MONGO_PORT: "27017"
  MONGO_DBNAME: "unifi"
  MONGO_AUTHSOURCE: "admin"
