apiVersion: v1
kind: Secret
metadata:
  name: radarr-init-secret-env
  namespace: media
type: Opaque
stringData:
  RADARR__POSTGRES__PASSWORD: ${quote}${DEFAULT_POSTGRES_RADARR_USER_PASSWORD}${quote}
  PGHOST: ${DEFAULT_POSTGRES_HOST}
  PGUSER: "postgres"
  PGPASSWORD: ${quote}${DEFAULT_POSTGRES_SYSTEM_PASSWORD}${quote}
  MAIN_DB: "radarr_main"
  LOG_DB: "radarr_log"
---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret-env
  namespace: media
type: Opaque
stringData:
  RADARR__POSTGRES__PASSWORD: ${quote}${DEFAULT_POSTGRES_RADARR_USER_PASSWORD}${quote}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-env
  namespace: media
data:
  RADARR__APP__THEME: "dark"
  # RADARR__SERVER__URLBASE: "/movies"
  RADARR__POSTGRES__HOST: ${DEFAULT_POSTGRES_HOST}
  RADARR__POSTGRES__PORT: ${quote}${DEFAULT_POSTGRES_PORT}${quote}
  RADARR__POSTGRES__MAINDB: radarr_main
  RADARR__POSTGRES__LOGDB: radarr_log
  RADARR__POSTGRES__USER: ${DEFAULT_POSTGRES_RADARR_USER}
  RADARR__LOG__ANALYTICSENABLED: "false"
  RADARR__LOG__LEVEL: "INFO"
