---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-env
  namespace: media
data:
  RADARR__APP__THEME: "dark"
  # RADARR__SERVER__URLBASE: "/movies"
  RADARR__POSTGRES__HOST: ${quote}${DEFAULT_POSTGRES_HOST}${quote}
  RADARR__POSTGRES__PORT: ${quote}${DEFAULT_POSTGRES_PORT}${quote}
  RADARR__POSTGRES__MAINDB: radarr_main
  RADARR__POSTGRES__LOGDB: radarr_log
  RADARR__POSTGRES__USER: ${DEFAULT_POSTGRES_RADARR_USER}
  RADARR__LOG__ANALYTICSENABLED: "false"
  RADARR__LOG__LEVEL: "INFO"
