---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  releaseName: homepage
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: "^2.0.1"
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: homepage-helm-values
