---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: homepage
  namespace: default
spec:
  parentRefs:
    - name: gateway
      namespace: edge
  hostnames:
    - "my.home.${DOMAIN_NAME}"
    - "my.${DOMAIN_NAME}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: homepage
          port: 3000
