---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./meilisearch.yaml
  - ./meilisearch-pvc.yaml
  - ./meilisearch-secret.yaml
configMapGenerator:
  - name: meilisearch-helm-values
    namespace: default
    files:
      - values.yaml=./helm-values.yaml
configurations:
  - kustomizeconfig.yaml
