---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meilisearch
  namespace: default
spec:
  releaseName: meilisearch
  interval: 30m
  chart:
    spec:
      chart: meilisearch
      version: "^0.20.0"
      sourceRef:
        kind: HelmRepository
        name: meilisearch
        namespace: flux-system
      reconcileStrategy: Revision
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: meilisearch-helm-values
