---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql-vecto
  namespace: default
spec:
  releaseName: postgresql-vecto
  interval: 30m
  chart:
    spec:
      chart: cluster
      version: ">=0.4.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
  valuesFrom:
    - kind: ConfigMap
      name: postgresql-vecto-helm-values
