apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${quote}${CERTIFICATE_NAME_HOME}${quote}"
  namespace: edge
spec:
  secretName: "${quote}${CERTIFICATE_NAME_HOME}${quote}"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "${quote}${CERTIFICATE_DOMAIN_HOME}${quote}"
