---
apiVersion: v1
kind: Secret
metadata:
  name: icloudpd-secret
type: Opaque
stringData:
  apple_id: ${quote}${APPLE_ID}${quote}
  telegram_token: ${quote}${TELEGRAM_BOT_TOKEN}${quote}
  telegram_chat_id: ${quote}${TELEGRAM_BOT_CHAT_ID}${quote}
