apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-backup-secret
  namespace: security
type: Opaque
stringData:
  DB_TYPE: "postgresql"
  PG_HOST: ${SECURITY_POSTGRES_HOST}
  PG_PORT: ${quote}${SECURITY_POSTGRES_PORT}${quote}
  PG_DBNAME: ${SECURITY_POSTGRES_VAULTWARDEN_DATABASE}
  PG_USERNAME: ${SECURITY_POSTGRES_VAULTWARDEN_USER}
  PG_PASSWORD: ${quote}${SECURITY_POSTGRES_VAULTWARDEN_USER_PASSWORD}${quote}
  ZIP_PASSWORD: ${quote}${VAULTWARDEN_BACKUP_ZIP_PASSWORD}${quote}
---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-rclone-secret
  namespace: security
stringData:
  rclone.conf: |
    [BitwardenBackup]
    type = drive
    scope = drive
    client_id = ${quote}${VAULTWARDEN_BACKUP_CLIENT_ID}${quote}
    client_secret = ${quote}${VAULTWARDEN_BACKUP_CLIENT_SECRET}${quote}
    token = ${quote}${VAULTWARDEN_BACKUP_TOKEN}${quote}

#"[BitwardenBackup]\ntype = drive\nscope = drive\nteam_drive =\nclient_id = ${quote}${VAULTWARDEN_BACKUP_CLIENT_ID}${quote}\nclient_secret = ${quote}${VAULTWARDEN_BACKUP_CLIENT_SECRET}${quote}\ntoken = ${quote}${VAULTWARDEN_BACKUP_TOKEN}${quote}\n"
#{{ printf "[BitwardenBackup]\ntype = drive\nscope = drive\nteam_drive =\nclient_id = %s\nclient_secret = %s\ntoken = %s\n" .Values.vaultwarden.backup.client_id .Values.vaultwarden.backup.client_secret .Values.vaultwarden.backup.token | b64enc }}
