apiVersion: v1
kind: Secret
metadata:
  name: fritzbox-cloudflare-dyndns-credentials
  namespace: edge
type: Opaque
stringData:
  user: ${quote}${FRITZBOX_DDNS_USERNAME}${quote}
  password: ${quote}${FRITZBOX_DDNS_PASSWORD}${quote}
