---
apiVersion: v1
kind: Secret
metadata:
  name: configarr
type: Opaque
stringData:
  secrets.yml: |
    SONARR_API_KEY: ${quote}${SONARR_API_KEY}${quote}
    RADARR_API_KEY: ${quote}${RADARR_API_KEY}${quote}
