---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configarr
data:
  config.yml: |
    trashGuideUrl: https://github.com/TRaSH-Guides/Guides
    recyclarrConfigUrl: https://github.com/recyclarr/config-templates

    sonarr:
      series:
        base_url: http://sonarr.media.svc.cluster.local
        api_key: !secret SONARR_API_KEY

        quality_definition:
          type: series

        include:
          - template: dca7e5e9e99c703bcbdaaa471dd40e98
            source: TRASH

        custom_formats: []
    radarr:
      movies:
        base_url: http://radarr.media.svc.cluster.local
        api_key: !secret RADARR_API_KEY

        quality_definition:
          type: series

        include:
          - template: 2b90e905c99490edc7c7a5787443748b
            source: TRASH

        custom_formats: []