---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: configarr
spec:
  schedule: "0 20 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: configarr
              image: ghcr.io/raydak-labs/configarr:1.27.0
              imagePullPolicy: Always
              tty: true # for color support
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 500m
                  memory: 256Mi
              volumeMounts:
                - mountPath: /app/repos # Cache repositories
                  name: app-data
                  subPath: configarr-repos
                - name: config
                  mountPath: /app/config/config.yml
                  subPath: config.yml
                - name: secret
                  mountPath: /app/config/secrets.yml
                  subPath: secrets.yml
          volumes:
            - name: app-data
              emptyDir: {}
            - name: config
              configMap:
                name: configarr
            - name: secret
              secret:
                secretName: configarr
          restartPolicy: Never
