---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configarr-cj.yaml
  - ./configarr-cm.yaml
  - ./configarr-secret.yaml