---
apiVersion: v1
kind: Service
metadata:
  name: better-bahn
  namespace: default
  labels:
    app.kubernetes.io/name: better-bahn
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: better-bahn
