---
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
  namespace: media
type: Opaque
stringData:
  # Redis configuration - cross-namespace reference to default namespace
  REDIS_HOSTNAME: ${quote}${REDIS_HOST}${quote}
  REDIS_PORT: "6379"
  REDIS_USERNAME: ${quote}${IMMICH_REDIS_USER}${quote}
  REDIS_PASSWORD: ${quote}${IMMICH_REDIS_PASSWORD}${quote}
  REDIS_DBINDEX: "0"
  # PostgreSQL configuration - postgresql-vecto cluster in default namespace
  DB_HOSTNAME: ${quote}${DEFAULT_POSTGRES_HOST}${quote}
  DB_PORT: ${quote}${DEFAULT_POSTGRES_PORT}${quote}
  DB_DATABASE_NAME: ${quote}${DEFAULT_POSTGRES_IMMICH_DATABASE}${quote}
  # Note: DB_USERNAME and DB_PASSWORD are set via env in helm values referencing postgresql-vecto-immich-auth
