---
fullnameOverride: pocket-id

podAnnotations:
  reloader.stakater.com/auto: "true"

image:
  repository: ghcr.io/pocket-id/pocket-id
  tag: v2.4.0

config:
  appUrl: "https://id.${DOMAIN_NAME}"

existingSecret: "pocket-id-secret"

persistence:
  enabled: true
  size: 1Gi
  storageClass: "local-path"

service:
  type: ClusterIP
  port: 1411

ingress:
  enabled: false

resources:
  requests:
    memory: 64Mi
    cpu: 10m
  limits:
    memory: 256Mi
    cpu: 500m
