---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pocket-id-pvc.yaml
  - ./pocket-id-secret.yaml
  - ./pocket-id-deploy.yaml
  - ./pocket-id-svc.yaml
  - ./pocket-id-ingressroute.yaml
  - ./pocket-id-oidc-secret.yaml
  - ./pocket-id-oidc-middleware.yaml
