---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-secret
  namespace: security
type: Opaque
stringData:
  TRUST_PROXY: "true"
  UI_CONFIG_DISABLED: "true"
  ENCRYPTION_KEY: ${quote}${POCKET_ID_ENCRYPTION_KEY}${quote}
  SMTP_HOST: ${RESEND_SMTP_HOST}
  SMTP_PORT: ${quote}${RESEND_SMTP_PORT}${quote}
  SMTP_FROM: id@${DOMAIN_NAME}
  SMTP_USER: ${RESEND_SMTP_USER}
  SMTP_PASSWORD: ${quote}${RESEND_API_KEY}${quote}
  SMTP_TLS: "tls"
  APP_URL: "https://id.${DOMAIN_NAME}"
