---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-data
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
