---
apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-oidc-secret
  namespace: security
type: Opaque
stringData:
  pluginSecret: ${POCKET_ID_OIDC_PLUGIN_SECRET}
  providerClientSecret: ${POCKET_ID_OIDC_CLIENT_SECRET}
