---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./crowdsec.yaml
  - ./crowdsec-init-secret-env.yaml
configMapGenerator:
  - name: crowdsec-helm-values
    files:
      - values.yaml=helm-values.yaml
configurations:
  - kustomizeconfig.yaml
