---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-wa-config-pvc
  namespace: media
spec:
  storageClassName: "local-path"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
