---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./calibre-wa-deploy.yaml
  - ./calibre-wa-ingressroute.yaml
  - ./calibre-wa-pvc.yaml
