# https://github.com/elfhosted/containers/tree/main/apps/readarr
apiVersion: v1
kind: Secret
metadata:
  name: readarr-init-secret-env
  namespace: media
type: Opaque
stringData:
  READARR__POSTGRES_PASSWORD: ${quote}${DEFAULT_POSTGRES_READARR_USER_PASSWORD}${quote}
  PGUSER: "postgres"
  PGPASSWORD: ${quote}${DEFAULT_POSTGRES_SYSTEM_PASSWORD}${quote}
  PGHOST: ${DEFAULT_POSTGRES_HOST}
  MAIN_DB: "readarr_main"
  LOG_DB: "readarr_log"
  CACHE_DB: "readarr_cache"
---
apiVersion: v1
kind: Secret
metadata:
  name: readarr-secret-env
  namespace: media
type: Opaque
stringData:
  READARR__POSTGRES_PASSWORD: ${quote}${DEFAULT_POSTGRES_READARR_USER_PASSWORD}${quote}
  READARR__API_KEY: ${quote}${READARR_API_KEY}${quote}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: readarr-env
  namespace: media
data:
  # READARR__URL_BASE: "/books"
  READARR__AUTHENTICATION_METHOD: "Forms"
  READARR__AUTHENTICATION_REQUIRED: "true"
  READARR__POSTGRES_HOST: ${DEFAULT_POSTGRES_HOST}
  READARR__POSTGRES_PORT: ${quote}${DEFAULT_POSTGRES_PORT}${quote}
  READARR__POSTGRES_MAIN_DB: readarr_main
  READARR__POSTGRES_LOG_DB: readarr_log
  READARR__POSTGRES_CACHE_DB: readarr_cache
  READARR__POSTGRES_USER: ${DEFAULT_POSTGRES_READARR_USER}
  READARR__ANALYTICS_ENABLED: "false"
  READARR__LOG_LEVEL: "info"
