---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb2
spec:
  interval: 30m
  chart:
    spec:
      chart: influxdb2
      version: "^2.1.2"
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
      reconcileStrategy: Revision
  valuesFrom:
    - kind: ConfigMap
      name: influxdb2-helm-values
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
