---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-credentials
  namespace: edge
type: Opaque
stringData:
  apiToken: "${CLOUDFLARE_API_TOKEN}"
  userEmail: "${ACME_EMAIL}"
  zonesToUpdate: "${CLOUDFLARE_ZONES_TO_UPDATE}"
