---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cloudflare-dns-credentials-secret.yaml
configMapGenerator:
  - name: cert-manager-helm-values
    files:
      - values.yaml=helm-values.yaml
configurations:
  - kustomizeconfig.yaml
