---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: ${quote}${MONGODB_ROOT_PASSWORD}${quote}
  MONGO_USER: ${quote}${MONGODB_UNIFI_USER}${quote}
  MONGO_PASS: ${quote}${MONGODB_UNIFI_PASSWORD}${quote}
  MONGO_DBNAME: "unifi"
  MONGO_AUTHSOURCE: "admin"
