---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-scripts
  namespace: default
data:
  init-unifi.sh: |-
    #!/bin/bash
    if which mongosh > /dev/null 2>&1; then
      mongo_init_bin='mongosh'
    else
      mongo_init_bin='mongo'
    fi
    js=$(printf 'db.createUser({user:"%s",pwd:"%s",roles:["clusterMonitor",{db:"%s",role:"dbOwner"},{db:"%s_stat",role:"dbOwner"},{db:"%s_audit",role:"dbOwner"},{db:"%s_restore",role:"dbOwner"}]})' \
      "$MONGO_USER" "$MONGO_PASS" \
      "$MONGO_DBNAME" "$MONGO_DBNAME" "$MONGO_DBNAME" "$MONGO_DBNAME")
    "$mongo_init_bin" admin \
      -u "$MONGO_INITDB_ROOT_USERNAME" \
      -p "$MONGO_INITDB_ROOT_PASSWORD" \
      --authenticationDatabase admin \
      --eval "$js"
