---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-scripts
  namespace: default
data:
  init-unifi.sh: |-
    #!/bin/bash
    if which mongosh > /dev/null 2>&1; then
      mongo_init_bin='mongosh'
    else
      mongo_init_bin='mongo'
    fi
    DB=$MONGO_DBNAME
    "$mongo_init_bin" <<EOF
    use $MONGO_AUTHSOURCE
    db.auth("$MONGO_INITDB_ROOT_USERNAME", "$MONGO_INITDB_ROOT_PASSWORD")
    db.createUser({
      user: "$MONGO_USER",
      pwd: "$MONGO_PASS",
      roles: [
        "clusterMonitor",
        { db: "$DB", role: "dbOwner" },
        { db: "${DB}_stat", role: "dbOwner" },
        { db: "${DB}_audit", role: "dbOwner" },
        { db: "${DB}_restore", role: "dbOwner" }
      ]
    })
    EOF
