---
apiVersion: v1
kind: Secret
metadata:
  name: pvc-backup-secret
  namespace: default
type: Opaque
stringData:
  PROXMOX_BACKUP_SERVER_PASSWORD: ${quote}${PROXMOX_BACKUP_SERVER_PASSWORD}${quote}
  PROXMOX_BACKUP_SERVER_REPOSITORY: ${quote}${PROXMOX_BACKUP_SERVER_REPOSITORY}${quote}
  PROXMOX_BACKUP_SERVER_FINGERPRINT: ${quote}${PROXMOX_BACKUP_SERVER_FINGERPRINT}${quote}
  TELEGRAM_BOT_TOKEN: ${quote}${TELEGRAM_BOT_TOKEN}${quote}
  TELEGRAM_CHAT_ID: ${quote}${TELEGRAM_BOT_CHAT_ID}${quote}
