---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ssl-header
  namespace: edge
spec:
  headers:
    customRequestHeaders:
      Connection: keep-alive, Upgrade
      Upgrade: WebSocket
