---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-hcloud-backup-config
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    app.kubernetes.io/name: immich-hcloud-backup
data:
  config.yaml: |-
    # gorestic-homelab configuration for Immich hcloud Backup

    # Restic repository configuration
    restic:
      repository: "rest:https://${H_CLOUD_HOST}/geck/immich/"
      password: "${RESTIC_PASSWORD}"
      rest_user: "${RESTIC_REST_USERNAME}"
      rest_password: "${RESTIC_REST_PASSWORD}"
      fail_on_locked: "false"

    # Backup configuration
    backup:
      paths:
        - /data/photos
      tags:
        - immich
      host: "k3s"

    # Retention policy
    retention:
      keep_daily: 0
      keep_weekly: 3
      keep_monthly: 0

    # Repository integrity check
    check:
      enabled: true
      subset: "1%"

    # PostgreSQL database backup
    postgres:
      host: "${POSTGRES_HOST}"
      port: 5432
      database: "immich"
      username: "${POSTGRES_USER}"
      password: "${POSTGRES_PASSWORD}"
      format: "custom"

    pushover:
      app_token: "${PUSHOVER_BACKUPS_TOKEN}"
      user_key: "${PUSHOVER_USER_KEY}"
      priority: 1
