apiVersion: v1
kind: Secret
metadata:
  name: security-postgres-auth
  namespace: security
type: Opaque
stringData:
  postgres-password: ${quote}${SECURITY_POSTGRES_SYSTEM_PASSWORD}${quote}
  password: ${quote}${SECURITY_POSTGRES_DEFAULT_USER_PASSWORD}${quote}
