---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: security-postgres-auth
  namespace: security
type: Opaque
stringData:
  postgres-password: ${quote}${SECURITY_POSTGRES_SYSTEM_PASSWORD}${quote}
  password: ${quote}${SECURITY_POSTGRES_DEFAULT_USER_PASSWORD}${quote}
