apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: security
type: Opaque
stringData:
  ADMIN_TOKEN: ${quote}${VAULTWARDEN_ADMIN_TOKEN}${quote}
  DATABASE_URL: postgres://${SECURITY_POSTGRES_VAULTWARDEN_USER}:${SECURITY_POSTGRES_VAULTWARDEN_USER_PASSWORD}@${SECURITY_POSTGRES_HOST}:${SECURITY_POSTGRES_PORT}/${SECURITY_POSTGRES_VAULTWARDEN_DATABASE}
#{{ printf "postgres://%s:%s@%s:%s/%s"
#.Values.persistence.postgresql.security.postgresVaultwardenUser
#.Values.persistence.postgresql.security.postgresVaultwardenPassword
#.Values.persistence.postgresql.security.host
#.Values.persistence.postgresql.security.port
#.Values.persistence.postgresql.security.postgresVaultwardenDatabase
# | b64enc }}
