---
apiVersion: v1
kind: Service
metadata:
  name: printer-k1c
  namespace: default
  labels:
    app.kubernetes.io/name: printer-k1c
spec:
  type: ExternalName
  externalName: 192.168.178.190
  ports:
    - port: 4409
      targetPort: 4409
