---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: bouncer
  namespace: security
spec:
  plugin:
    bouncer:
      enabled: true
      Enabled: "true"
      logLevel: INFO
      crowdsecMode: stream
      crowdsecLapiScheme: http
      crowdsecLapiHost: crowdsec-service.security.svc.cluster.local
      crowdsecLapiKey: ${quote}${CROWDSEC_BOUNCER_KEY_TRAEFIK}${quote}
      forwardedHeadersTrustedIPs:
        # private class ranges
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
      clientTrustedIPs:
        # private class ranges
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
