---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gateway-only-ipallowlist
  namespace: edge
spec:
  ipAllowList:
    sourceRange:
        - 127.0.0.1/32
        - ${quote}${TRAEFIK_GATEWAY_CIDR}${quote}
