---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik-middleware.yaml
  - ./crowdsec-bouncer.yaml
  - ./local-ip-allow-middleware.yaml
  - ./gateway-only-middleware.yaml
  - ./ssl-header-middleware.yaml
  - ./websocket-middleware.yaml
