---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.31.0-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-oidc-secret
  namespace: edge
type: Opaque
stringData:
  clientId: "${CLUSTER_HOME_OIDC_POCKETID_CLIENT_ID}"
  clientSecret: "${CLUSTER_HOME_OIDC_POCKETID_CLIENT_SECRET}"
  sessionSecret: "${CLUSTER_HOME_OIDC_SESSION_SECRET}"
