---
apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-oidc-secret
  namespace: edge
type: Opaque
stringData:
  clientId: "${CLUSTER_HOME_OIDC_POCKETID_CLIENT_ID}"
  clientSecret: "${CLUSTER_HOME_OIDC_POCKETID_CLIENT_SECRET}"
