---
apiVersion: v1
kind: Service
metadata:
  name: traefik-incluster
  namespace: edge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: traefik-edge
    app.kubernetes.io/name: traefik
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: websecure
