---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: websocket
  namespace: edge
spec:
  headers:
    customResponseHeaders:
      Upgrade: "websocket"
      Connection: "upgrade"
      Strict-Transport-Security: "max-age=31536000 ; includeSubDomains" # Optional: Enable HSTS for WebSocket traffic
